/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.item-column[_ngcontent-%COMP%]\n{\n	 padding: 16px;\n	 width: 33%;\n}\n\n.item-column-body[_ngcontent-%COMP%]\n{\n	height: calc(100% - 73px);\n	max-height: 100%;\n	overflow-y: auto;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL21lZGlhL1NlY29uZGFyeS9NeSBTdHVmZi9XZWJzaXRlcy9iZWFydHJhY2tzL2Fzc2V0cy9hcHAvYnJvd3NlL2Jyb3dzZS5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL21lZGlhL1NlY29uZGFyeS9NeSBTdHVmZi9XZWJzaXRlcy9iZWFydHJhY2tzL2Fzc2V0cy9hcHAvYnJvd3NlL2Jyb3dzZS5jb21wb25lbnQuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
