/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../assets/app/app.module';
import * as i2 from '../../../assets/app/app.component';
import * as i3 from '../../node_modules/angular2-lightbox/lightbox-overlay.component.ngfactory';
import * as i4 from '../../node_modules/angular2-lightbox/lightbox.component.ngfactory';
import * as i5 from '../../node_modules/@angular/material/typings/index.ngfactory';
import * as i6 from './browse/browse.component.ngfactory';
import * as i7 from './dashboard/dashboard.component.ngfactory';
import * as i8 from './genres/genres.component.ngfactory';
import * as i9 from './search/search.component.ngfactory';
import * as i10 from './user/profile.component.ngfactory';
import * as i11 from './user/signup.component.ngfactory';
import * as i12 from './app.component.ngfactory';
import * as i13 from '@angular/common';
import * as i14 from '@angular/platform-browser';
import * as i15 from '@angular/material';
import * as i16 from '@angular/animations/browser';
import * as i17 from '@angular/platform-browser/animations';
import * as i18 from '@angular/flex-layout/media-query/breakpoints/break-points-token';
import * as i19 from '@angular/flex-layout/media-query/breakpoints/break-points-provider';
import * as i20 from '@angular/flex-layout/media-query/breakpoints/break-point-registry';
import * as i21 from '@angular/flex-layout/media-query/match-media';
import * as i22 from '@angular/flex-layout/media-query/media-monitor';
import * as i23 from '@angular/flex-layout/media-query/media-monitor-provider';
import * as i24 from '@angular/flex-layout/media-query/observable-media';
import * as i25 from '@angular/flex-layout/media-query/observable-media-provider';
import * as i26 from '@angular/forms';
import * as i27 from '@angular/http';
import * as i28 from 'angular2-lightbox/lightbox-config.service';
import * as i29 from 'angular2-lightbox/lightbox-event.service';
import * as i30 from 'angular2-lightbox/lightbox.service';
import * as i31 from 'angular2-notifications/src/push-notifications/services/push-notifications.service';
import * as i32 from '@angular/animations';
import * as i33 from '@angular/router';
import * as i34 from '../../../assets/app/player/player.service';
import * as i35 from '../../../assets/app/tracks/track.service';
import * as i36 from '../../../assets/app/user/user.service';
import * as i37 from '@angular/flex-layout/media-query/_module';
import * as i38 from '@angular/flex-layout/flexbox/_module';
import * as i39 from '../../../assets/app/browse/browse.component';
import * as i40 from '../../../assets/app/dashboard/dashboard.component';
import * as i41 from '../../../assets/app/genres/genres.component';
import * as i42 from '../../../assets/app/search/search.component';
import * as i43 from '../../../assets/app/user/profile.component';
import * as i44 from '../../../assets/app/user/signup.component';
import * as i45 from 'angular2-focus/src/focus.module';
import * as i46 from 'angular2-lightbox/lightbox.module';
import * as i47 from 'angular2-notifications/src/push-notifications.module';
export const AppModuleNgFactory:i0.NgModuleFactory<i1.AppModule> = i0.ɵcmf(i1.AppModule,
    [i2.AppComponent],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.LightboxOverlayComponentNgFactory,i4.LightboxComponentNgFactory,
              i5.MdDialogContainerNgFactory,i5.MdDatepickerContentNgFactory,i5.MdSnackBarContainerNgFactory,
              i5.SimpleSnackBarNgFactory,i5.TooltipComponentNgFactory,i6.BrowseComponentNgFactory,
              i7.DashboardComponentNgFactory,i8.GenresComponentNgFactory,i9.SearchComponentNgFactory,
              i10.ProfileComponentNgFactory,i11.SignupComponentNgFactory,i12.AppComponentNgFactory]],
              [3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(5120,i0.LOCALE_ID,
          i0.ɵm,[[3,i0.LOCALE_ID]]),i0.ɵmpd(4608,i13.NgLocalization,i13.NgLocaleLocalization,
          [i0.LOCALE_ID]),i0.ɵmpd(5120,i0.APP_ID,i0.ɵf,([] as any[])),i0.ɵmpd(5120,
          i0.IterableDiffers,i0.ɵk,([] as any[])),i0.ɵmpd(5120,i0.KeyValueDiffers,
          i0.ɵl,([] as any[])),i0.ɵmpd(4608,i14.DomSanitizer,i14.ɵe,[i14.DOCUMENT]),
          i0.ɵmpd(6144,i0.Sanitizer,(null as any),[i14.DomSanitizer]),i0.ɵmpd(4608,
              i14.HAMMER_GESTURE_CONFIG,i15.GestureConfig,([] as any[])),i0.ɵmpd(5120,
              i14.EVENT_MANAGER_PLUGINS,(p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
                return [new i14.ɵDomEventsPlugin(p0_0),new i14.ɵKeyEventsPlugin(p1_0),
                    new i14.ɵHammerGesturesPlugin(p2_0,p2_1)];
              },[i14.DOCUMENT,i14.DOCUMENT,i14.DOCUMENT,i14.HAMMER_GESTURE_CONFIG]),
          i0.ɵmpd(4608,i14.EventManager,i14.EventManager,[i14.EVENT_MANAGER_PLUGINS,
              i0.NgZone]),i0.ɵmpd(135680,i14.ɵDomSharedStylesHost,i14.ɵDomSharedStylesHost,
              [i14.DOCUMENT]),i0.ɵmpd(4608,i14.ɵDomRendererFactory2,i14.ɵDomRendererFactory2,
              [i14.EventManager,i14.ɵDomSharedStylesHost]),i0.ɵmpd(5120,i16.AnimationDriver,
              i17.ɵc,([] as any[])),i0.ɵmpd(5120,i16.ɵAnimationStyleNormalizer,i17.ɵd,
              ([] as any[])),i0.ɵmpd(4608,i16.ɵAnimationEngine,i17.ɵb,[i16.AnimationDriver,
              i16.ɵAnimationStyleNormalizer]),i0.ɵmpd(5120,i0.RendererFactory2,i17.ɵe,
              [i14.ɵDomRendererFactory2,i16.ɵAnimationEngine,i0.NgZone]),i0.ɵmpd(6144,
              i14.ɵSharedStylesHost,(null as any),[i14.ɵDomSharedStylesHost]),i0.ɵmpd(4608,
              i0.Testability,i0.Testability,[i0.NgZone]),i0.ɵmpd(4608,i14.Meta,i14.Meta,
              [i14.DOCUMENT]),i0.ɵmpd(4608,i14.Title,i14.Title,[i14.DOCUMENT]),i0.ɵmpd(5120,
              i18.BREAKPOINTS,i19.DEFAULT_BREAKPOINTS_PROVIDER_FACTORY,([] as any[])),
          i0.ɵmpd(4608,i20.BreakPointRegistry,i20.BreakPointRegistry,[i18.BREAKPOINTS]),
          i0.ɵmpd(4608,i21.MatchMedia,i21.MatchMedia,[i0.NgZone]),i0.ɵmpd(5120,i22.MediaMonitor,
              i23.MEDIA_MONITOR_PROVIDER_FACTORY,[[3,i22.MediaMonitor],i20.BreakPointRegistry,
                  i21.MatchMedia]),i0.ɵmpd(5120,i24.ObservableMedia,i25.OBSERVABLE_MEDIA_PROVIDER_FACTORY,
              [[3,i24.ObservableMedia],i21.MatchMedia,i20.BreakPointRegistry]),i0.ɵmpd(4608,
              i26.ɵi,i26.ɵi,([] as any[])),i0.ɵmpd(4608,i26.FormBuilder,i26.FormBuilder,
              ([] as any[])),i0.ɵmpd(4608,i27.BrowserXhr,i27.BrowserXhr,([] as any[])),
          i0.ɵmpd(4608,i27.ResponseOptions,i27.BaseResponseOptions,([] as any[])),
          i0.ɵmpd(5120,i27.XSRFStrategy,i27.ɵb,([] as any[])),i0.ɵmpd(4608,i27.XHRBackend,
              i27.XHRBackend,[i27.BrowserXhr,i27.ResponseOptions,i27.XSRFStrategy]),
          i0.ɵmpd(4608,i27.RequestOptions,i27.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,
              i27.Http,i27.ɵc,[i27.XHRBackend,i27.RequestOptions]),i0.ɵmpd(4608,i28.LightboxConfig,
              i28.LightboxConfig,([] as any[])),i0.ɵmpd(4608,i29.LightboxEvent,i29.LightboxEvent,
              ([] as any[])),i0.ɵmpd(4608,i30.Lightbox,i30.Lightbox,[i0.ComponentFactoryResolver,
              i0.Injector,i0.ApplicationRef,i28.LightboxConfig,i29.LightboxEvent,i14.DOCUMENT]),
          i0.ɵmpd(4608,i29.LightboxWindowRef,i29.LightboxWindowRef,([] as any[])),
          i0.ɵmpd(4608,i31.PushNotificationsService,i31.PushNotificationsService,([] as any[])),
          i0.ɵmpd(4608,i15.Platform,i15.Platform,([] as any[])),i0.ɵmpd(5120,i15.ScrollDispatcher,
              i15.ɵf,[[3,i15.ScrollDispatcher],i0.NgZone,i15.Platform]),i0.ɵmpd(5120,
              i15.ViewportRuler,i15.ɵd,[[3,i15.ViewportRuler],i15.ScrollDispatcher]),
          i0.ɵmpd(4608,i15.ScrollStrategyOptions,i15.ScrollStrategyOptions,[i15.ScrollDispatcher,
              i15.ViewportRuler]),i0.ɵmpd(5120,i15.OverlayContainer,i15.ɵb,[[3,i15.OverlayContainer]]),
          i0.ɵmpd(4608,i15.ɵv,i15.ɵv,[i15.ViewportRuler]),i0.ɵmpd(4608,i15.Overlay,
              i15.Overlay,[i15.ScrollStrategyOptions,i15.OverlayContainer,i0.ComponentFactoryResolver,
                  i15.ɵv,i0.ApplicationRef,i0.Injector,i0.NgZone]),i0.ɵmpd(5120,i15.FocusOriginMonitor,
              i15.FOCUS_ORIGIN_MONITOR_PROVIDER_FACTORY,[[3,i15.FocusOriginMonitor],
                  i0.NgZone,i15.Platform]),i0.ɵmpd(5120,i15.UniqueSelectionDispatcher,
              i15.ɵj,[[3,i15.UniqueSelectionDispatcher]]),i0.ɵmpd(4608,i15.ɵa,i15.ɵa,
              ([] as any[])),i0.ɵmpd(4608,i15.InteractivityChecker,i15.InteractivityChecker,
              [i15.Platform]),i0.ɵmpd(4608,i15.FocusTrapFactory,i15.FocusTrapFactory,
              [i15.InteractivityChecker,i15.Platform,i0.NgZone]),i0.ɵmpd(5120,i15.LiveAnnouncer,
              i15.ɵi,[[3,i15.LiveAnnouncer],[2,i15.LIVE_ANNOUNCER_ELEMENT_TOKEN],i15.Platform]),
          i0.ɵmpd(4608,i15.MdDialog,i15.MdDialog,[i15.Overlay,i0.Injector,[2,i13.Location],
              [3,i15.MdDialog]]),i0.ɵmpd(4608,i15.MdDatepickerIntl,i15.MdDatepickerIntl,
              ([] as any[])),i0.ɵmpd(5120,i15.MdIconRegistry,i15.ICON_REGISTRY_PROVIDER_FACTORY,
              [[3,i15.MdIconRegistry],[2,i27.Http],i14.DomSanitizer]),i0.ɵmpd(4608,
              i15.MdSnackBar,i15.MdSnackBar,[i15.Overlay,i15.LiveAnnouncer,[3,i15.MdSnackBar]]),
          i0.ɵmpd(4608,i32.AnimationBuilder,i17.ɵBrowserAnimationBuilder,[i0.RendererFactory2]),
          i0.ɵmpd(5120,i33.ActivatedRoute,i33.ɵf,[i33.Router]),i0.ɵmpd(4608,i33.NoPreloading,
              i33.NoPreloading,([] as any[])),i0.ɵmpd(6144,i33.PreloadingStrategy,
              (null as any),[i33.NoPreloading]),i0.ɵmpd(135680,i33.RouterPreloader,
              i33.RouterPreloader,[i33.Router,i0.NgModuleFactoryLoader,i0.Compiler,
                  i0.Injector,i33.PreloadingStrategy]),i0.ɵmpd(4608,i33.PreloadAllModules,
              i33.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,i33.ROUTER_INITIALIZER,
              i33.ɵi,[i33.ɵg]),i0.ɵmpd(5120,i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
            return [p0_0];
          },[i33.ROUTER_INITIALIZER]),i0.ɵmpd(4608,i34.PlayerService,i34.PlayerService,
              [i35.TrackService,i27.Http,i30.Lightbox,i31.PushNotificationsService]),
          i0.ɵmpd(4608,i36.UserService,i36.UserService,[i27.Http]),i0.ɵmpd(512,i13.CommonModule,
              i13.CommonModule,([] as any[])),i0.ɵmpd(1024,i0.ErrorHandler,i14.ɵa,
              ([] as any[])),i0.ɵmpd(1024,i0.NgProbeToken,() => {
            return [i33.ɵb()];
          },([] as any[])),i0.ɵmpd(512,i33.ɵg,i33.ɵg,[i0.Injector]),i0.ɵmpd(1024,i0.APP_INITIALIZER,
              (p0_0:any,p0_1:any,p1_0:any) => {
                return [i14.ɵc(p0_0,p0_1),i33.ɵh(p1_0)];
              },[[2,i14.NgProbeToken],[2,i0.NgProbeToken],i33.ɵg]),i0.ɵmpd(512,i0.ApplicationInitStatus,
              i0.ApplicationInitStatus,[[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,
              i0.ɵe,[i0.NgZone,i0.ɵConsole,i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,
                  i0.ApplicationInitStatus]),i0.ɵmpd(2048,i0.ApplicationRef,(null as any),
              [i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,i0.ApplicationModule,[i0.ApplicationRef]),
          i0.ɵmpd(512,i14.BrowserModule,i14.BrowserModule,[[3,i14.BrowserModule]]),
          i0.ɵmpd(512,i37.MediaQueriesModule,i37.MediaQueriesModule,([] as any[])),
          i0.ɵmpd(512,i38.FlexLayoutModule,i38.FlexLayoutModule,([] as any[])),i0.ɵmpd(512,
              i26.ɵba,i26.ɵba,([] as any[])),i0.ɵmpd(512,i26.FormsModule,i26.FormsModule,
              ([] as any[])),i0.ɵmpd(512,i26.ReactiveFormsModule,i26.ReactiveFormsModule,
              ([] as any[])),i0.ɵmpd(1024,i33.ɵa,i33.ɵd,[[3,i33.Router]]),i0.ɵmpd(512,
              i33.UrlSerializer,i33.DefaultUrlSerializer,([] as any[])),i0.ɵmpd(512,
              i33.ChildrenOutletContexts,i33.ChildrenOutletContexts,([] as any[])),
          i0.ɵmpd(256,i33.ROUTER_CONFIGURATION,{},([] as any[])),i0.ɵmpd(1024,i13.LocationStrategy,
              i33.ɵc,[i13.PlatformLocation,[2,i13.APP_BASE_HREF],i33.ROUTER_CONFIGURATION]),
          i0.ɵmpd(512,i13.Location,i13.Location,[i13.LocationStrategy]),i0.ɵmpd(512,
              i0.Compiler,i0.Compiler,([] as any[])),i0.ɵmpd(512,i0.NgModuleFactoryLoader,
              i0.SystemJsNgModuleLoader,[i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),
          i0.ɵmpd(1024,i33.ROUTES,() => {
            return [[{path:'',redirectTo:'/browse',pathMatch:'full'},{path:'browse',
                component:i39.BrowseComponent},{path:'dashboard',component:i40.DashboardComponent},
                {path:'genres',component:i41.GenresComponent},{path:'search',component:i42.SearchComponent},
                {path:'profile',component:i43.ProfileComponent},{path:'signup',component:i44.SignupComponent}]];
          },([] as any[])),i0.ɵmpd(1024,i33.Router,i33.ɵe,[i0.ApplicationRef,i33.UrlSerializer,
              i33.ChildrenOutletContexts,i13.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i33.ROUTES,i33.ROUTER_CONFIGURATION,[2,i33.UrlHandlingStrategy],
              [2,i33.RouteReuseStrategy]]),i0.ɵmpd(512,i33.RouterModule,i33.RouterModule,
              [[2,i33.ɵa],[2,i33.Router]]),i0.ɵmpd(512,i27.HttpModule,i27.HttpModule,
              ([] as any[])),i0.ɵmpd(512,i45.FocusModule,i45.FocusModule,([] as any[])),
          i0.ɵmpd(512,i46.LightboxModule,i46.LightboxModule,([] as any[])),i0.ɵmpd(512,
              i47.PushNotificationsModule,i47.PushNotificationsModule,([] as any[])),
          i0.ɵmpd(512,i15.CompatibilityModule,i15.CompatibilityModule,([] as any[])),
          i0.ɵmpd(256,i15.MATERIAL_SANITY_CHECKS,true,([] as any[])),i0.ɵmpd(512,i15.MdCommonModule,
              i15.MdCommonModule,[[2,i14.DOCUMENT],[2,i15.MATERIAL_SANITY_CHECKS]]),
          i0.ɵmpd(512,i15.PlatformModule,i15.PlatformModule,([] as any[])),i0.ɵmpd(512,
              i15.ScrollDispatchModule,i15.ScrollDispatchModule,([] as any[])),i0.ɵmpd(512,
              i15.MdRippleModule,i15.MdRippleModule,([] as any[])),i0.ɵmpd(512,i15.MdSelectionModule,
              i15.MdSelectionModule,([] as any[])),i0.ɵmpd(512,i15.MdOptionModule,
              i15.MdOptionModule,([] as any[])),i0.ɵmpd(512,i15.PortalModule,i15.PortalModule,
              ([] as any[])),i0.ɵmpd(512,i15.OverlayModule,i15.OverlayModule,([] as any[])),
          i0.ɵmpd(512,i15.MdAutocompleteModule,i15.MdAutocompleteModule,([] as any[])),
          i0.ɵmpd(512,i15.StyleModule,i15.StyleModule,([] as any[])),i0.ɵmpd(512,i15.MdButtonModule,
              i15.MdButtonModule,([] as any[])),i0.ɵmpd(512,i15.MdButtonToggleModule,
              i15.MdButtonToggleModule,([] as any[])),i0.ɵmpd(512,i15.MdCardModule,
              i15.MdCardModule,([] as any[])),i0.ɵmpd(512,i15.MdChipsModule,i15.MdChipsModule,
              ([] as any[])),i0.ɵmpd(512,i15.ObserveContentModule,i15.ObserveContentModule,
              ([] as any[])),i0.ɵmpd(512,i15.MdCheckboxModule,i15.MdCheckboxModule,
              ([] as any[])),i0.ɵmpd(512,i15.A11yModule,i15.A11yModule,([] as any[])),
          i0.ɵmpd(512,i15.MdDialogModule,i15.MdDialogModule,([] as any[])),i0.ɵmpd(512,
              i15.MdDatepickerModule,i15.MdDatepickerModule,([] as any[])),i0.ɵmpd(512,
              i15.MdExpansionModule,i15.MdExpansionModule,([] as any[])),i0.ɵmpd(512,
              i15.MdLineModule,i15.MdLineModule,([] as any[])),i0.ɵmpd(512,i15.MdGridListModule,
              i15.MdGridListModule,([] as any[])),i0.ɵmpd(512,i15.MdIconModule,i15.MdIconModule,
              ([] as any[])),i0.ɵmpd(512,i15.MdInputModule,i15.MdInputModule,([] as any[])),
          i0.ɵmpd(512,i15.MdListModule,i15.MdListModule,([] as any[])),i0.ɵmpd(512,
              i15.MdMenuModule,i15.MdMenuModule,([] as any[])),i0.ɵmpd(512,i15.MdProgressBarModule,
              i15.MdProgressBarModule,([] as any[])),i0.ɵmpd(512,i15.MdProgressSpinnerModule,
              i15.MdProgressSpinnerModule,([] as any[])),i0.ɵmpd(512,i15.MdRadioModule,
              i15.MdRadioModule,([] as any[])),i0.ɵmpd(512,i15.MdSelectModule,i15.MdSelectModule,
              ([] as any[])),i0.ɵmpd(512,i15.MdSidenavModule,i15.MdSidenavModule,([] as any[])),
          i0.ɵmpd(512,i15.RtlModule,i15.RtlModule,([] as any[])),i0.ɵmpd(512,i15.MdSliderModule,
              i15.MdSliderModule,([] as any[])),i0.ɵmpd(512,i15.MdSlideToggleModule,
              i15.MdSlideToggleModule,([] as any[])),i0.ɵmpd(512,i15.MdSnackBarModule,
              i15.MdSnackBarModule,([] as any[])),i0.ɵmpd(512,i15.MdTabsModule,i15.MdTabsModule,
              ([] as any[])),i0.ɵmpd(512,i15.MdToolbarModule,i15.MdToolbarModule,([] as any[])),
          i0.ɵmpd(512,i15.MdTooltipModule,i15.MdTooltipModule,([] as any[])),i0.ɵmpd(512,
              i15.MaterialModule,i15.MaterialModule,([] as any[])),i0.ɵmpd(512,i17.BrowserAnimationsModule,
              i17.BrowserAnimationsModule,([] as any[])),i0.ɵmpd(512,i1.AppModule,
              i1.AppModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL21lZGlhL1NlY29uZGFyeS9NeSBTdHVmZi9XZWJzaXRlcy9iZWFydHJhY2tzL2Fzc2V0cy9hcHAvYXBwLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9tZWRpYS9TZWNvbmRhcnkvTXkgU3R1ZmYvV2Vic2l0ZXMvYmVhcnRyYWNrcy9hc3NldHMvYXBwL2FwcC5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
