/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['#PageContent[_ngcontent-%COMP%] {\n	padding: 50px;\n}\n\nmd-toolbar[_ngcontent-%COMP%] {\n	background-color: rgb(40, 40, 40);\n	box-shadow: 2px 2px 5px 5px rgba(0, 0, 0, 0.12);\n	margin: 0px;\n	padding: 0px;\n}\n\n[md-button][_ngcontent-%COMP%] {\n	text-transform: lowercase;\n}\n\nmd-toolbar[_ngcontent-%COMP%]   [md-button][_ngcontent-%COMP%]\n{\n	color: rgba(255, 255, 255, 0.54);\n	height: 100%;\n	padding: 16px 32px;\n	width: 24%;\n}\n\nmd-toolbar[_ngcontent-%COMP%]   [md-button].active[_ngcontent-%COMP%]\n{\n	border-bottom: 2px solid rgba(255, 255, 255, 0.87);\n}\n\nmd-toolbar[_ngcontent-%COMP%]   [md-button][disabled][_ngcontent-%COMP%]\n{\n	cursor: not-allowed;\n}\n\nmd-sidenav-container[_ngcontent-%COMP%] {\n	background-color: rgb(27, 27, 27);\n	height: 100%;\n}\n\nmd-sidenav[_ngcontent-%COMP%] {\n	padding: 8px;\n	width: 256px;\n}\n\nmd-sidenav[_ngcontent-%COMP%]   button[_ngcontent-%COMP%] {\n	display: inline-block;\n	text-align: left;\n	width: 100%;\n}\n\nmd-sidenav[_ngcontent-%COMP%]   button[_ngcontent-%COMP%]   md-icon[_ngcontent-%COMP%] {\n	margin-right: 6px;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL21lZGlhL1NlY29uZGFyeS9NeSBTdHVmZi9XZWJzaXRlcy9iZWFydHJhY2tzL2Fzc2V0cy9hcHAvYXBwLmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vbWVkaWEvU2Vjb25kYXJ5L015IFN0dWZmL1dlYnNpdGVzL2JlYXJ0cmFja3MvYXNzZXRzL2FwcC9hcHAuY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
